version: '3.8'

services:
  web:
    build: ..
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://agriculture_user:agriculture_password@db:5432/agriculture_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    volumes:
      - ../app:/app/app
      - ../uploads:/app/uploads
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=agriculture_db
      - POSTGRES_USER=agriculture_user
      - POSTGRES_PASSWORD=agriculture_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ../app/static:/var/www/static
      - ./ssl:/etc/ssl/certs
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
